# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  algorithmia-ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Algorithmia CI
      uses: algorithmiaio/algorithmia-ci-action@v0.1.0-rc5
      with:
        # Your typical Algorithmia API key
        regular_api_key: ${{ secrets.regular_api_key }}
        # Your algorithm management capable Algorithmia API key
        mgmt_api_key: ${{ secrets.mgmt_api_key }}
        # The API address for the Algorithmia Cluster you wish to connect to
        api_address: https://api.algorithmia.com
        # The name of the Algorithm you want to test
        algorithm_name: zeryx/algorithmia_ci_simple
        # A list of Json Case objects that describe the desired test cases
        test_cases: '[{"case_name":"hello_world", "input":"algorithmia", "expected_output":"hello algorithmia"}]'
        # identifier to describe how to promote this release
        version_schema: minor

